- name: check pip and virtualenv are installed
  yum: name={{ item }}
       state=present
  with_items:
    - python-pip
    - python-virtualenv
  tags:
    - download

- name: create application folder
  file: state=directory
        path=/usr/local/xs-authserver/
        owner=root
        group=root
        mode=0644

- name: install xs-authserver and requirements from pypi into a venv
  pip: name={{ item }}
       virtualenv=/usr/local/xs-authserver/venv
       extra_args='--no-deps --use-wheel --find-links http://xsce.activitycentral.com/wheelhouse/'
  with_items:
    - Flask==0.10.1
    - Jinja2==2.7.1
    - MarkupSafe==0.18
    - Werkzeug==0.9.4
    - gunicorn==18.0
    - itsdangerous==0.23
    - wsgiref==0.1.2
    - xs-authserver==0.1.5
  tags:
    - download

- name: Configure xs-authserver
  template: backup=yes
            src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode={{ item.mode }}
  with_items:
    - src: xs-authserver.env.j2
      dest: /etc/sysconfig/xs-authserver
      mode: 0644
    - src: xs-authserver.service.j2
      dest: /etc/systemd/system/xs-authserver.service
      mode: 0644
      mode: 0644

- name: init database
  command: /usr/local/xs-authserver/venv/bin/xs-authserverctl initdb
  ignore_errors: yes
  environment:
    XS_AUTHSERVER_DATABASE: /usr/local/xs-authserver/data.db

- name: Enable xs-authserver service
  service: name=xs-authserver
           enabled=yes
           state=started

- name: add xs-authserver to service list
  ini_file: dest='{{ service_filelist }}'
            section=xs-authserver
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
    - option: name
      value: XS-authserver
    - option: description
      value: 'xs-authserver implements a seamless web authentication service
             using XO laptop registration capabilities.  It is heavily inspired
             by the Moodle OLPC-XS authentication plugin'
    - option: port
      value: 5000
    - option: path
      value: /
